### ISSUE TITLE
get_sid returning 403 response

### ISSUE THREAD

**Issue by thegreekjester** [nathanrchn/perplexityai#10]
I am using the most recent update and am running into the following error when using the perplexity class: 
Traceback (most recent call last):
  File "/Users/panagiotis/Documents/Syft/perplexityai/script.py", line 3, in <module>
    perplexity = Perplexity()
  File "/Users/panagiotis/Documents/Syft/perplexityai/Perplexity.py", line 42, in __init__
    self.sid: str = self.get_sid()
  File "/Users/panagiotis/Documents/Syft/perplexityai/Perplexity.py", line 67, in get_sid
    response = loads(self.session.get(
  File "/opt/anaconda3/envs/delphi/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/envs/delphi/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/envs/delphi/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Looking at previous issues, it looks like this was previously accounted for by adding a User agent string but recently it is occurring again. I have tried providing a "real" looking user agent as well as run the requests through a proxy but no luck. Any other ideas on how to resolve this?

**Comment by phamxtien** [comment]
get_sid return
```
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
	</head>
	<body class="no-js">
    <div class="main-wrapper" role="main">
    	<div class="main-content">
    		<noscript>
					<div id="challenge-error-title">
						<div class="h2">
							<span class="icon-wrapper">
								<div class="heading-icon warning-icon"></div>
							</span>
							<span id="challenge-error-text">Enable JavaScript and cookies to continue</span>
						</div>
					</div>
				</noscript>
			</div>
		</div>
		<script>
			(function(){window._cf_chl_opt={cvId: '2',cZone: 'www.perplexity.ai',cType: 'managed',cNounce: '44935',cRay: '8013ae1e6c524993',cHash: '13f9a646c3ed9e4',cUPMDTk: "\/socket.io\/?EIO=4&transport=polling&t=szcVxpE&__cf_chl_tk=LBtTlMlcMzwLzhFImw1JZdISZij4Vq_.MnmP3BEPO1Q-1693803745-0-gaNycGzNDBA",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "/socket.io/?EIO=4&amp;transport=polling&amp;t=szcVxpE&amp;__cf_chl_f_tk=LBtTlMlcMzwLzhFImw1JZdISZij4Vq_.MnmP3BEPO1Q-1693803745-0-gaNycGzNDBA",md: "5PDJuHJJwKLU7Va_gFCsGzb4jyxfmo2xE.waFKs_v2U-1693803745-0-AfKooTrkHU78HRoh9JqPyjQsqfPCxzhVd1YV_eEXpPHoHPVjn_d3hW2WINgoUpU7WCTRDkA3wVVNKYNbAJ3C688H0fwDidt1iXUUL5howUL0wihNBMzO0X2aD2xGhgP3dGHpbJWUMUOoOF8m9yBUeLqGPhnT853_LjgYcAZEC8exrOTrZhlULeV737GccH5sxh_f3fHH5mZxe8fDzvAsxG591WENVdlJWUgeMx3rPEHkxYft4oGLS3hMaWSX6SInnicAlqWOMU0QPkeWc8LQUzpHFQutLyp8Tf1rTmkL_gujVJnSxvSzoVflp2H90kMoygC15YsBsYqbJ4BqRG1jQUCWVs2rL5von9NpEs5O43tjTOu3MGogSsl5eoBWNX3KhddjDZK3gQPGi8ZkoLFq141R9GN7ZbU1E30hTujNhTH4iIOsWXwN-oadX28OefTwbZEtwAHdCx3M7cD49o45tC9NsqPM-nRt_MDmrvFWeWE-8u9CPZ6O03ml5edJchxDCy4eNK1V-r6W94ZWpBFkxbN9XV_9ZafbwZ1NM4InDZz4gKIydLjMQafH4XVTWz7tAteY9cpofHKhsZoxBr07dhg2HIluVvs9-FryUp12Muix6_tUlTTQC-6hCsePVsxPxVxYwl3oaEEe0cB-_9vcgtafsRFwU0Y5iPq2Jm-JY3KgYVhfZOKLYXl5dhJwK4DM0l1VvLoLXtZy-0NWeODDIZwTS4FfBGQJuKVES1OaNsZkE3TQoJm-BMx0K5KbWVJkCQ7J4rUW1Z-isu-kSOlDk7-f6Df_jc2zfzl-Lij6RKGoH-kpFDqCyxK9BOWHDnnokIvSmS6dfGmr6vzYyZn-32c5Wt0TiiI6MZ-QfeE6-tNURtliLpAFoQkHBOyzIfbKkPYHb9Mf0cYxy_D9M6HaL4KLxceffSvnvDtzcVldIipBA1PElx7PVpc1utP1vfJT0d33z6kuJUfobI9PRLBAFlAxR8GZfQq_HT4oBQoOLeQdsH-spgTMwNNUSii2a9wKksTJeNdlCeWLVjLRDPdgoW6Af9tuGUmRayKLNO6aLeinfF8OGQaqRGm-4B9ddLu7-PbTXhyLtcGgyYwo0no7Uk8r-1o4xCqwNAjxm6958kByFiNqcsq4h168O3wrrfvSH6-rtrzwhaBRRqApPTkJu6zLVjlkuW3_VRlI_It-Ce2wIaKWxREdnINL1_pXOIdvT37bnm7fUSIhMgi90u_vDZVVxSUXeUfjfvtuDyUeuU8bmn14Hl_3Rt5YBE3q3Xa2m5cK-DG5vQcak_fyVjs7a-ibm78Yapje6wBiqEsJxKpTScpwLccnuSfP3TxWhENQK1YpVLnQC5itbFb0SMLGUNqlTHDOG9goqNTTNH2hWrThjwGXhr-Qz8PqlfAfPHmVjvAvUDePY55GQQaNaHvQ1FURqxoxvvgMY_RWgHNJr4a4y1vjp2MMhPE2JvsHh-WMcVPxiFZw4CkHZmCEP6TTv2UP8joKtBtfCyLFYC0K7DXJH2yIqLEJ83iJf7X7ydB7B_TexMlmz6FxDXajDzjgBd1nyMNjLsSmuELpXsrKVWc7GEjuXdRe-ZXWXO87Ue23m3wt0jGKuO1YZ3su9znlXmFOES57umFaDuyCubI5RdAXBZeXtCId7Mp4OCedkjJgk6RGqo7fTKQ6ChLtUSlPFZAPtAnTufXhZoTNaZDcx69lOGr-D5Xv50LSrQrjZpl0HgZyzi94xQL4mAs8vBmNnN9DrQxTHdTA1q1oQXr56voiKJHruJqfutgG_pOTOIcbhYpl5z50X53glOTZK_ynrs9chIYmZCKpYOTD_TRKUa1g52qg_9Ioexg_gCpPugNW25VNg3D3dGxANdz0HFHZFrqx_od4_9sdbaWMne29pw8KHgCIe_TAJVC5KZ3VPEzD0oi-fRAcAExMW6KGz-y5KkqMXZ7cvxg86lKGgR2daVzPopp_EoCMpybUdZRrvGsBl31S2QnRi0jboHPkZc6bvSmE_RinDCD84FyxsB2WjXOAUYfLrT8WPQ_gSUZEVY9iqRK-tJGRqIgbKo-hNVp0eDzjFPm0E0QXOThrVrZ9c236XPTagfrv7rbzyLjPI5HXtt5XTq5CB555NijXND1QAkdt7zxErozjuwrJJ7V0-3Q9oW0m6tVyNQNzt3pFIYc3gjSOo9mciOgJiqnD24AfY8qFs9vDH1YhCQEDab7EciR9-tGPjPWCu0cds2VyBekqhBH03w5m70KifMfbLToYJR4jboN8laeEVR4y3xX3YLBQlK4YvvwWW8we_ebqyl_WxwLnWc94y1GvAa-Zb12RlOcnWfzxZGSG6b7pjgUHblz8mw93P-qDHnSpFcWff4r4QvpKOx-vSdOmcmAgpe7Ttjb4BlCWZOZs22YGcuU93FOAvC--rqDNvqh8MRtiLt8ljVMVKlZiR3YzGz1RCNVdSwyIAkqZFxB9MPtSwCRJ6ahjL7V5-j3dv2ihsA2R8-WdxayGDeOUX1uv-XDCA_mHejEcLhq5-SULfQAHE4kEiVzBAH9EGIS7BTF7YbS9lLFdT-H9OrAvaSLW57uv2_aZ3dYQ9OyYwcYVOVPOTU0IVaN8p8PE8-uBonOBOubfBsbRNgKj0toTRGP8o83luR7Uacb-wH1HBZFaPJslI7HtDN_sidf_kyjXf0M3qC0BDjuYM-mw3CVO5rnjChh7y-FLuNe_51tSCzNcV7qKwA4wt623vwn0WGVw5Ils5X4nqx21huIqMCY82tCWe-Ul_zlXJnfU0a4ZGViN5_NLKY01VmCJMjMfCwstIN0K1sKesoeLuf4QHKTFycaAUkaHqZO9y441rmSARM1HGXXM8PBrJ6JLGDlQ8NUUsELw4ho38uMFKzu1yRu1NsOt7_2_wk83U1aZwY7K-88PdidLbu_DlA94ZeuiJChAVFi6TeQAu3CC4fv_J0xXJ0SdhLiFD8cchKUzZHAIYVrOD6fXo7rodHoF3k6K9iyePuY3DaOb3dij0F8iUlKpx_aEXsRcI3SvI2o",cRq: {ru: 'aHR0cHM6Ly93d3cucGVycGxleGl0eS5haS9zb2NrZXQuaW8vP0VJTz00JnRyYW5zcG9ydD1wb2xsaW5nJnQ9c3pjVnhwRQ==',ra: '',rm: 'R0VU',d: 'mtIvUK4zcwR/UyM65fyj5Mm+h00lhlk06tWjB4+f2TjwN99nAgkJeVkgyfq8hBS9XH8+lNHh/9tJP1EncBGWP261+zilYE2Dq1ZH719ApNUw1c2JQgJFXxK5iIAy0Mj41DuvG+ihtxRnPgXhpVSkMkFwNpF4o0AByhDy9L8wOo4O+5x4Bi2g168wpocAJXPnTl/M+1lwpw4myaNOyOnbeCf24YSmVMIT2LpoKWdY1hrcD9V9h9SUC8tiQRsv8CZ9MHAsCj34LwQM6gsn84D/qDCJl7RuXjbUJyfe6zyFFoqzK/xIzmakUXwQDRVUBnNi5qILG6ZaOKvS210vL8DHJTeutMOaETcyEqQ4+6gIb5r1GIUkqXy5xvNdYbnpePIs+WsLbMaBidZfM9jbsETP9dbh4NSXnBagHXQJB28H2j5qrGlm3XJiYulo3k50wS4BMYL0WuW5QIF1dx2/lfEs2p2mEQu0ufsi5bWCcUVy/t/FEylWXX9ayy7lDJ6wt5bJ1LWhAO25GUieNDqH7szInDxTj/hJsxfl6RH8TG51vZg=',t: 'MTY5MzgwMzc0NS4wMjcwMDA=',cT: Math.floor(Date.now() / 1000),m: 'hzbMeke+VaxGb9pv3DHc78nHS3XfSieFTqjzWoXqoTI=',i1: 'SMh8NafAL8Y2FBiCdTZx3g==',i2: 'I1/o+rEeql/BOsK+Es5cPA==',zh: 'NU8ixJjbvuzjjI0VYVlScfuo4FsYASw7wpJI5etvkPw=',uh: 'KLb8Am+6SKuORSqGZdzdoytsuHlOxI/GUNgcr5UJ9hw=',hh: 'Y4wbTy2+H//SzqXCr/ut8Fn8eNgcrMRWkXlJV1vMwRU=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8013ae1e6c524993';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/socket.io\/?EIO=4&transport=polling&t=szcVxpE&__cf_chl_rt_tk=LBtTlMlcMzwLzhFImw1JZdISZij4Vq_.MnmP3BEPO1Q-1693803745-0-gaNycGzNDBA" + window._cf_chl_opt.cOgUHash);
			cpo.onload = function() {history.replaceState(null, null, ogU);};}
			document.getElementsByTagName('head')[0].appendChild(cpo);}());
		</script>
	</body>
</html>
```

**Comment by phamxtien** [comment]
Can not by pass cloudflare :(

**Comment by praburamWAPKA** [comment]
> Can not by pass cloudflare :(

he he he simply create one discord channel and add official perpelxity bot, ask question and bot will print the data and tell the bot to made entry as text of db or bla bla bla

**Comment by nathanrchn** [comment]
I just changed the User-Agent from `""` to `Ask/2.2.1/334 (iOS; iPhone) isiOSOnMac/false` and the program works now. Cloudfare doesn't block this request anymore because it's a mobile User-Agent. Tell me if it works for you.
