### ISSUE TITLE
    raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by sarthak501** [nathanrchn/perplexityai#51]
Traceback (most recent call last):
  File "/home/runner/gp/main.py", line 3, in <module>
    perplexity = Perplexity()
  File "/home/runner/gp/.pythonlibs/lib/python3.10/site-packages/perplexity/perplexity.py", line 28, in __init__
    self.sid: str = self._get_sid()
  File "/home/runner/gp/.pythonlibs/lib/python3.10/site-packages/perplexity/perplexity.py", line 80, in _get_sid
    return loads(self.session.get(
  File "/nix/store/8w6mm5q1n7i7cs1933im5vkbgvjlglfn-python3-3.10.13/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/8w6mm5q1n7i7cs1933im5vkbgvjlglfn-python3-3.10.13/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/8w6mm5q1n7i7cs1933im5vkbgvjlglfn-python3-3.10.13/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by whvjvgf** [comment]
楼主，你有解决这个问题嘛？

**Comment by YoannDev90** [comment]
I guess the project is no longer being maintained. Unfortunately ...
