### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AtulRajVAASITS** [nathanrchn/perplexityai#58]
👦: hai
Traceback (most recent call last):
  File "d:\Working on\ml\research\test.py", line 956, in <module>
    for a in Perplexity().generate_answer(prompt):
             ^^^^^^^^^^^^
  File "d:\Working on\ml\research\research\Lib\site-packages\perplexityai\__init__.py", line 25, in __init__
    self.sid = loads(response)["sid"]
               ^^^^^^^^^^^^^^^
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alok.r\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alok.r\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AtulRajVAASITS** [comment]
I have taken the latest version

**Comment by QZepHyr** [comment]
me too

**Comment by BJarboe** [comment]
I have a workaround but kept running into issues.  Feel free to troubleshoot further, but I think I'm just gonna look for alternatives to perplexity with how many problems keep appearing.

Some necessary dependencies:
```
pip install selenium undetected_chromedriver setuptools
```

In perplexityai\\__init__.py:
```
from json import loads, dumps, JSONDecodeError
from selenium import webdriver
import undetected_chromedriver as uc
import re
```
Same file in Perplexity's class constructor.  Replace the response = (... line with this code block
```
        driver = uc.Chrome()
        driver.get(f"https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}")
        response = driver.page_source
        json_match = re.search(r'0(\{.*\})', response)
        if json_match:
            json_data = json_match.group(1)  # The JSON string we need
            try:
                parsed_data = loads(json_data)  # Parse JSON data
                sid = parsed_data["sid"]  # Access sid field
            except JSONDecodeError as e:
                print("Failed to parse JSON:", e)
        else:
            print("No JSON data found in response")
        driver.quit()
```

Basically it uses a headless browser to pass some security checks then filters the pulled html for the actual JSON with regex.  
Again it gets around this issue but another one comes up when asserting a POST request. 
Happy Troubleshooting :^)

**Comment by yly189** [comment]
[https://github.com/nathanrchn/perplexityai/issues/67#issuecomment-2553080949](url) Try this solution
