### ISSUE TITLE
TypeError: WebSocket.__init__() got an unexpected keyword argument 'url'

### ISSUE THREAD

**Issue by YoannDev90** [nathanrchn/perplexityai#64]
```shell
Traceback (most recent call last):
  File "c:\Users\user\Documents\GitHub\perplexityai\test.py", line 3, in <module>
    perplexity = Perplexity()
                 ^^^^^^^^^^^^
  File "c:\Users\user\Documents\GitHub\perplexityai\perplexity.py", line 39, in __init__
    self.ws: WebSocket = self._init_websocket()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Documents\GitHub\perplexityai\perplexity.py", line 149, in _init_websocket
    return WebSocket(
           ^^^^^^^^^^
TypeError: WebSocket.__init__() got an unexpected keyword argument 'url'
```

Any solution ?

**Comment by YoannDev90** [comment]
I guess the project is abandonned.
