### ISSUE TITLE
Hi, when I run the repo on service, it comes out this, how can I solve it? 

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [nathanrchn/perplexityai#7]
`>>> from Perplexity import Perplexity
>>> 
>>> perplexity = Perplexity()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/perplexityai/Perplexity.py", line 24, in __init__
    self.sid: str = self.get_sid()
  File "/root/perplexityai/Perplexity.py", line 48, in get_sid
    response = loads(self.session.get(
  File "/root/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> answer = perplexity.search("What is the meaning of life?")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'perplexity' is not defined
`

**Comment by nathanrchn** [comment]
First of all, make sure you have the latest version of the program, as I recently corrected this problem. Otherwise, it may be due to a network configuration or proxy.

**Comment by Lowlowlowlowlowlow** [comment]
> First of all, make sure you have the latest version of the program, as I recently corrected this problem. Otherwise, it may be due to a network configuration or proxy.

Got it, it may be due to the proxy I am using now, but how could I fix it?
